// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6-3X-Ag-lsAGSNItoCbp-0wdMRlF2PeQ',
    appId: '1:474911245185:web:d2a4e3aaef5ef7e7045e80',
    messagingSenderId: '474911245185',
    projectId: 'glowmate-73614',
    authDomain: 'glowmate-73614.firebaseapp.com',
    storageBucket: 'glowmate-73614.firebasestorage.app',
    measurementId: 'G-HCCW4CHL76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAETbqt_pza6MrqZ2ovNDSaf-3T92Iv-j8',
    appId: '1:474911245185:android:7a19ccb836e3b772045e80',
    messagingSenderId: '474911245185',
    projectId: 'glowmate-73614',
    storageBucket: 'glowmate-73614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2zQ4DX2l0JT5MFZUxQVvadUY2S5fuxa4',
    appId: '1:474911245185:ios:dbd8abf67ed78fc3045e80',
    messagingSenderId: '474911245185',
    projectId: 'glowmate-73614',
    storageBucket: 'glowmate-73614.firebasestorage.app',
    androidClientId: '474911245185-n0f1it5s2p31ej3dfre0dece04jib4v7.apps.googleusercontent.com',
    iosClientId: '474911245185-hu3q74o778jgpq492q82k4jbnl59ijlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.glowmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2zQ4DX2l0JT5MFZUxQVvadUY2S5fuxa4',
    appId: '1:474911245185:ios:dbd8abf67ed78fc3045e80',
    messagingSenderId: '474911245185',
    projectId: 'glowmate-73614',
    storageBucket: 'glowmate-73614.firebasestorage.app',
    androidClientId: '474911245185-n0f1it5s2p31ej3dfre0dece04jib4v7.apps.googleusercontent.com',
    iosClientId: '474911245185-hu3q74o778jgpq492q82k4jbnl59ijlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.glowmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6-3X-Ag-lsAGSNItoCbp-0wdMRlF2PeQ',
    appId: '1:474911245185:web:de23e36abf1c5f86045e80',
    messagingSenderId: '474911245185',
    projectId: 'glowmate-73614',
    authDomain: 'glowmate-73614.firebaseapp.com',
    storageBucket: 'glowmate-73614.firebasestorage.app',
    measurementId: 'G-QC68655B4Q',
  );
}
